#!/usr/bin/env python3
"""Generates tests/errmap_v3_cases.inc from the per-procedure error table in
docs/nfsv3/08-errors.md §8.2 (development plan §9 "错误映射" row: the whitelist unit test
is *derived from the research document*, so a doc/code divergence fails CI).

Table grammar handled: comma-separated status names with optional parenthetical notes
("ISDIR(设size)"), "（仅通用）"/"（仅通用 + IO）" rows, and inheritance rows
"同 CREATE（无 NOTSUPP）" / "同 CREATE + NOTSUPP, BADTYPE, PERM".

usage: gen_errmap_cases.py [--check]   (--check: exit 1 if the .inc is stale)
"""
import re, sys, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
doc = (root / "docs/nfsv3/08-errors.md").read_text(encoding="utf-8")
out_path = root / "tests/errmap_v3_cases.inc"

sec = doc.split("## 8.2", 1)[1].split("## 8.3", 1)[0]
rows = {}
order = []
for line in sec.splitlines():
    m = re.match(r"^\|\s*([A-Z]+)\s*\|\s*(.*?)\s*\|\s*$", line)
    if not m:
        continue
    proc, spec = m.group(1), m.group(2)
    order.append(proc)
    rows[proc] = spec

def parse(spec):
    spec = re.sub(r"（[^）]*）", lambda m: "" if "仅通用" in m.group(0) and "无" not in m.group(0) else m.group(0), spec)
    names = set()
    m = re.match(r"^同\s+([A-Z]+)(.*)$", spec)
    if m:
        base = set(parse(rows[m.group(1)]))
        rest = m.group(2)
        minus = re.findall(r"无\s*([A-Z_]+)", rest)
        for name in minus:
            base.discard(name)
        rest = re.sub(r"（[^）]*）", "", rest)
        rest = rest.lstrip(" +")
        names |= base
        spec = rest
    spec = re.sub(r"\([^)]*\)", "", spec)  # ASCII parentheticals
    spec = re.sub(r"（[^）]*）", "", spec)
    for tok in re.split(r"[,，]", spec):
        tok = tok.strip()
        if re.fullmatch(r"[A-Z_]+", tok) and tok != "IO":
            names.add(tok)
    return sorted(names)

enum = {  # doc name -> nfsv3::Status enumerator
    "PERM": "kPerm", "NOENT": "kNoent", "IO": "kIo", "NXIO": "kNxio", "ACCES": "kAcces",
    "EXIST": "kExist", "XDEV": "kXdev", "NODEV": "kNodev", "NOTDIR": "kNotdir",
    "ISDIR": "kIsdir", "INVAL": "kInval", "FBIG": "kFbig", "NOSPC": "kNospc",
    "ROFS": "kRofs", "MLINK": "kMlink", "NAMETOOLONG": "kNametoolong",
    "NOTEMPTY": "kNotempty", "DQUOT": "kDquot", "STALE": "kStale", "REMOTE": "kRemote",
    "BADHANDLE": "kBadhandle", "NOT_SYNC": "kNotSync", "BAD_COOKIE": "kBadCookie",
    "NOTSUPP": "kNotsupp", "TOOSMALL": "kToosmall", "SERVERFAULT": "kServerfault",
    "BADTYPE": "kBadtype", "JUKEBOX": "kJukebox",
}
procs = {p: "k" + p.capitalize().replace("Readdirplus", "Readdirplus") for p in order}
procs["READDIRPLUS"] = "kReaddirplus"

lines = ["// GENERATED by scripts/gen_errmap_cases.py from docs/nfsv3/08-errors.md §8.2 — do not",
         "// edit; regenerate (CI checks freshness).  One row per (procedure, documented status).",
         "// clang-format off"]
for p in order:
    for name in parse(rows[p]):
        if name not in enum:
            sys.exit(f"unknown status name {name} in row {p}")
        lines.append(f'{{Proc::{procs[p]}, Status::{enum[name]}, "{p}", "{name}"}},')
lines.append("// clang-format on")
text = "\n".join(lines) + "\n"

if "--check" in sys.argv:
    if not out_path.exists() or out_path.read_text() != text:
        sys.exit("tests/errmap_v3_cases.inc is stale: run scripts/gen_errmap_cases.py")
    print("errmap cases up to date")
else:
    out_path.write_text(text)
    print(f"wrote {out_path} ({len(lines) - 4} cases)")
